name: "Bug report: Nextcloud Server"
description: "Submit a report and help us improve Nextcloud Server"
title: "[Bug]: "
labels: ["bug", "0. Needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Nextcloud is a free and open-source project maintained and contributed to by over 800 (and growing!) generous and devoted individuals all around the world.
        #### ðŸ‘ Thank you for contributing your own time by making this report and helping make Nextcloud even better!
        #### Reminders:
        1. This is **not** a technical support or general troubleshooting channel. 
        2. The reader of your report may be volunteering their own time to help you, so please be patient and respectful of their time.
        2. You may never receive a direct response, but you report will be read by over 500 (!) maintainers and contributors.
        3. Someone **may** follow-up if more information is needed, but you **might not** receive a personal response.
        4. The priorities are: reviewing each report, triaging issues, and fixing known bugs.
        #### You can obtain [Enterprise support](https://nextcloud.com/support/) from Nextcloud GmbH or a [certified Nextcloud partner](https://nextcloud.com/partners/) if you run Nextcloud Server in a mission critical environment. In addition to helping fund development, it is the only way to receive a guaranteed and timely response.
        ### âš ï¸ We require that everyone agree to the following when submitting a new bug report: âš ï¸
        #### These points help ensure that everyone can be focused on addressing bug reports - your bug report - and that you get the response or help you truly need is as timely manner as possible.
        1. This is not a technical support question or a general troubleshooting query. *If it could be, posting your query to the [Nextcloud Community Forum](https://help.nextcloud.com/) may get you assistance faster.*
        2. This seems to be bug, not a local/environment specific issue. *If unsure, posting your query to the [Nextcloud Community Forum](https://help.nextcloud.com/) first can provide clarity.*
        3. This issue does not seem to already be reported. *You may [search existing open bugs](https://github.com/nextcloud/server/issues?q=is%3Aissue+sort%3Acreated-desc+is%3Aopen+label%3Abug) and [search recently closed bugs](https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aclosed+sort%3Acreated-desc+label%3Abug). Tip: If your bug has already been reported by someone else, give their report a ðŸ‘ to help us prioritize it.*
        4. A supported version of Server is in-use and all apps are up-to-date. *See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.*
        5. I've reviewed Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
  - type: checkboxes
    id: before-posting
    attributes:
      label: Click here
      options:
        - label: I agree.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: |
        Provide a brief description of the bug you're experiencing.
        Tip: If applicable, screenshots can be uploaded into any text window to help explain your problem.
      placeholder: |
        A perfect description is unnecessary, but a concise and approachable description makes it more likely your report can be quickly reviewed, prioritized, and addressed by our busy volunteers, community members, and developers.
        Extra details or context can also be provided at the end of this form in **Additional info**.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: |
        How do you trigger this bug? Please walk us through it step by step.
      placeholder: |
        Example:
        \ 
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        \
        Describe the steps someone else would likely need to go through to reproduce the bug.
        Tip: The better your instructions the fastesr your bug can be triaged and addressed. 
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      description: |
        Select installation method you've used.
        _Describe the method in the "Additional info" section if you chose "Other"._
      options:
        - "Community Web installer on a VPS or web space"
        - "Community Manual installation with Archive"
        - "Community Docker image"
        - "Community NextcloudPi appliance"
        - "Community SNAP package"
        - "Community VM appliance"
        - "Other Community project"
        - "Official All-in-One appliance"
  - type: dropdown
    id: nextcloud-version
    attributes:
      label: Nextcloud Server version
      description: |
        Select Nextcloud Server version.
        _Versions not listed here are not maintained and not supported anymore_
      options:
        - "25"
        - "26"
        - "27"
        - "master"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: |
        Select operating system where Nextcloud Server is installed.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Debian/Ubuntu"
        - "RHEL/CentOS"
        - "Other"
  - type: dropdown
    id: php
    attributes:
      label: PHP engine version
      description: |
        Select PHP engine version serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "PHP 7.4"
        - "PHP 8.0"
        - "PHP 8.1"
        - "PHP 8.2"
        - "Other"
  - type: dropdown
    id: webserver
    attributes:
      label: Web server
      description: |
        Select Webserver serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Apache (supported)"
        - "Nginx"
        - "Other"
  - type: dropdown
    id: database
    attributes:
      label: Database engine version
      description: |
        Select Database engine serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "MySQL"
        - "MariaDB"
        - "PostgreSQL"
        - "SQlite"
        - "Oracle"
        - "Other"
  - type: dropdown
    id: fresh
    attributes:
      label: Is this bug present after an update or on a fresh install?
      description: |
        Select if bug is present after an update or on a fresh install.
      options:
        - "Updated from a MINOR version (ex. 22.1 to 22.2)"
        - "Upgraded to a MAJOR version (ex. 22 to 23)"
        - "Fresh Nextcloud Server install"
  - type: dropdown
    id: encryption
    attributes:
      label: Are you using the Nextcloud Server Encryption module?
      description: Select if encryption is Enabled on your Nextcloud Server.
      options:
        - "Encryption is Enabled"
        - "Encryption is Disabled"
  - type: checkboxes
    id: users
    attributes:
      label: What user-backends are you using?
      description: |
        Select **all** user-backends Enabled on your Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
      - label: "Default user-backend _(database)_"
      - label: "LDAP/ Active Directory"
      - label: "SSO - SAML"
      - label: "Other"
  - type: textarea
    id: configs
    attributes:
      label: Configuration report
      description: |
        Provide information about your configuration.
        Not required, but your bug report may take longer to review.
      placeholder: |
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ config:list system
        php occ config:list system
        ./occ config:list system
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: apps
    attributes:
      label: List of activated Apps
      description: |
        Provide information about your apps.
      placeholder: |
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ app:list
        php occ app:list
        ./occ app:list
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-signingstatus
    attributes:
      label: Nextcloud code integrity status
      description: |
        Confirms integrity of Nextcloud code.
      placeholder: |
        First, login as Admin user into your Nextcloud, then access this URL:
        ```shell
        https://yournextcloud.tld/index.php/settings/integrity/failed 
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-log
    attributes:
      label: Nextcloud Logs
      description: |
        Provide Nextcloud logs lines.
      placeholder: |
        Copy relevent contents from `data/nextcloud.log` or click **Copy->Copy RAW** from *Administration settings->Logging* (`/settings/admin/logging`) in the web interface
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional conext
      description: Add any other context about the problem here.
      placeholder: |
        (ex. browser console errors, software versions).
