name: "Bug report: Nextcloud Server"
description: "Submit a report and help us improve Nextcloud Server"
title: "[Bug]: "
labels: ["bug", "0. Needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### ðŸ‘ Thank you for contributing to our project!
        Please note Nextcloud Server is a **free and open-source** project. Most people volunteer their own time to help you, so please, be patient as well as respectful of their time.
        This is **not** a technical support or general troubleshooting channel - you may never receive a direct response, but you report will be read by over 500 (!) maintainers and contributors.
        Someone **may** follow-up if more information is needed, but you **might not** receive a personal response. The priorities are: reviewing each report, triaging issues, and fixing known and reported bugs.
        If you use Nextcloud Server and it is critical to your mission, you may obtain [Enterprise support](https://nextcloud.com/support/) from Nextcloud GmbH or a [Nextcloud *certified* partner](https://nextcloud.com/partners/).
  - type: checkboxes
    id: before-posting
    attributes:
      label: "âš ï¸ This issue respects the following points: âš ï¸"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: |
            This is not a technical support question or a general troubleshooting query.
            *If it could be, posting your query to the [Nextcloud Community Forum](https://help.nextcloud.com/) may get you assistance faster.*
          required: true
        - label: |
            This appears to be **bug**, not local/environment specific issue.
            *If unsure, posting your query to the [Nextcloud Community Forum](https://help.nextcloud.com/) first can provide clarity.*
          required: true
        - label: |
            This issue does not seem to already be reported.
            [Search existing open bugs](https://github.com/nextcloud/server/issues?q=is%3Aissue+sort%3Acreated-desc+is%3Aopen+label%3Abug) and [Search recently closed bugs](https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aclosed+sort%3Acreated-desc+label%3Abug).
            *Tip: If your bug is already reported by someone else, give it a ðŸ‘ to help us prioritize it.*
          required: true
        - label: Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
          required: true
        - label: I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        Provide a brief description of the bug you're experiencing.
      placeholder: |
        A perfect description is unnecessary, but a concise and approachable description makes it more likely your report can be quickly reviewed, prioritized, and addressed by our busy volunteers, community members, and developers.
        Any extra context or additional details can be provided at the end of this form.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: |
        "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        Describe the steps someone else would likely need to go through to reproduce the bug.
        The better your description is the fastesr your bug can be reviewed and addressed. 
        Example: (1. Go 'here', 2. Click 'there'..-) 
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen instead.
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      description: |
        Select installation method you've used.
        _Describe the method in the "Additional info" section if you chose "Other"._
      options:
        - "Community Web installer on a VPS or web space"
        - "Community Manual installation with Archive"
        - "Community Docker image"
        - "Community NextcloudPi appliance"
        - "Community SNAP package"
        - "Community VM appliance"
        - "Other Community project"
        - "Official All-in-One appliance"
  - type: dropdown
    id: nextcloud-version
    attributes:
      label: Nextcloud Server version
      description: |
        Select Nextcloud Server version.
        _Versions not listed here are not maintained and not supported anymore_
      options:
        - "25"
        - "26"
        - "27"
        - "master"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: |
        Select operating system where Nextcloud Server is installed.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Debian/Ubuntu"
        - "RHEL/CentOS"
        - "Other"
  - type: dropdown
    id: php
    attributes:
      label: PHP engine version
      description: |
        Select PHP engine version serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "PHP 7.4"
        - "PHP 8.0"
        - "PHP 8.1"
        - "PHP 8.2"
        - "Other"
  - type: dropdown
    id: webserver
    attributes:
      label: Web server
      description: |
        Select Webserver serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Apache (supported)"
        - "Nginx"
        - "Other"
  - type: dropdown
    id: database
    attributes:
      label: Database engine version
      description: |
        Select Database engine serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "MySQL"
        - "MariaDB"
        - "PostgreSQL"
        - "SQlite"
        - "Oracle"
        - "Other"
  - type: dropdown
    id: fresh
    attributes:
      label: Is this bug present after an update or on a fresh install?
      description: |
        Select if bug is present after an update or on a fresh install.
      options:
        - "Updated from a MINOR version (ex. 22.1 to 22.2)"
        - "Upgraded to a MAJOR version (ex. 22 to 23)"
        - "Fresh Nextcloud Server install"
  - type: dropdown
    id: encryption
    attributes:
      label: Are you using the Nextcloud Server Encryption module?
      description: Select if encryption is Enabled on your Nextcloud Server.
      options:
        - "Encryption is Enabled"
        - "Encryption is Disabled"
  - type: checkboxes
    id: users
    attributes:
      label: What user-backends are you using?
      description: |
        Select **all** user-backends Enabled on your Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
      - label: "Default user-backend _(database)_"
      - label: "LDAP/ Active Directory"
      - label: "SSO - SAML"
      - label: "Other"
  - type: textarea
    id: configs
    attributes:
      label: Configuration report
      description: |
        Provide information about your configuration.
        Not required, but your bug report may take longer to review.
      placeholder: |
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ config:list system
        php occ config:list system
        ./occ config:list system
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: apps
    attributes:
      label: List of activated Apps
      description: |
        Provide information about your apps.
      placeholder: |
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ app:list
        php occ app:list
        ./occ app:list
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-signingstatus
    attributes:
      label: Nextcloud code integrity status
      description: |
        Confirms integrity of Nextcloud code.
      placeholder: |
        First, login as Admin user into your Nextcloud, then access this URL:
        ```shell
        https://yournextcloud.tld/index.php/settings/integrity/failed 
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-log
    attributes:
      label: Nextcloud Logs
      description: |
        Provide Nextcloud logs lines.
      placeholder: |
        Copy relevent contents from `data/nextcloud.log` or a use **Copy->Copy RAW** from *Administration settings->Logging* `/settings/admin/logging` section:
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any additional information you think might be related to the issue
      placeholder: |
        (ex. browser console errors, software versions).
