name: "🚀 Enhancement Idea"
description: "Suggest an idea for this project"
title: "[Feature] "
labels:
  - enhancement
  - "0. Needs triage"
# type frontmatter is not used in Issue Forms; labels above replace it

body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Nextcloud!

  - type: markdown
    attributes:
      value: |
        **SECURITY MATTER? Please report potential security bugs via [Nextcloud's HackerOne](https://hackerone.com/nextcloud) profile instead of creating a public issue.**
        See the [Nextcloud security policy](https://nextcloud.com/security/) for further details.

  - type: textarea
    attributes:
      label: Instructions
      description: "Submitter: Please retain this field's content as-is; it will be automatically prepended at the top of your Issue so that readers of your idea know how to contribute to your suggestion."
      value: |
        ### Like this suggestion?
        * Use the 👍 reaction to show that you are interested in the same feature.
        * Please don't comment without relevant implementation information (extra “+1” noise makes triage harder).
        * Subscribe to receive notifications on status changes and new comments.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of the problem (e.g. what frustrates you, what gap exists).
      placeholder: "I'm always frustrated when ... / It is hard to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen from a user’s perspective.
      placeholder: "I would like it if ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Other approaches or workarounds and why they are less ideal.
      placeholder: "Alternative 1: ... (drawback: ...)\nAlternative 2: ..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, logs, references, or screenshots that help clarify the request.
      placeholder: "Screenshots, links to discussions, related issues, mockups..."
    validations:
      required: false
